name: sparrow
services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=sparrow-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d sparrow-dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/sparrow-dev?sslmode=disable
      - GIN_MODE=debug
      - REDIS_ADDRESS=redis:6379
    entrypoint:
      [ "/app/start.sh" ]
    command: [ "/app/main" ]
volumes:
  data-volume: