// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Draft struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	SuggestionID pgtype.UUID
	DraftText    string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type Postsuggestion struct {
	ID             pgtype.UUID
	PromptID       pgtype.UUID
	SuggestionText string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type Prompt struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	PromptText string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type Scheduledpost struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	DraftID       pgtype.UUID
	ScheduledTime pgtype.Timestamp
	Status        string
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type Socialaccount struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Platform       string
	AccountName    string
	AccountEmail   string
	AccessToken    string
	IDToken        string
	TokenExpiresAt pgtype.Timestamp
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type User struct {
	ID           pgtype.UUID
	Username     pgtype.Text
	Email        string
	PasswordHash pgtype.Text
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
