// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: post_schedules.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSchedule = `-- name: DeleteSchedule :one
DELETE FROM post_schedules
WHERE id = $1
RETURNING id, user_id, post_id, social_account_id, scheduled_time, executed_time, status, created_at, updated_at
`

func (q *Queries) DeleteSchedule(ctx context.Context, id pgtype.UUID) (PostSchedule, error) {
	row := q.db.QueryRow(ctx, deleteSchedule, id)
	var i PostSchedule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.SocialAccountID,
		&i.ScheduledTime,
		&i.ExecutedTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostScheduleByID = `-- name: GetPostScheduleByID :one
SELECT id, user_id, post_id, scheduled_time, status, created_at, updated_at
FROM post_schedules
WHERE id = $1
`

type GetPostScheduleByIDRow struct {
	ID            pgtype.UUID      `json:"id"`
	UserID        pgtype.UUID      `json:"user_id"`
	PostID        pgtype.UUID      `json:"post_id"`
	ScheduledTime pgtype.Timestamp `json:"scheduled_time"`
	Status        string           `json:"status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetPostScheduleByID(ctx context.Context, id pgtype.UUID) (GetPostScheduleByIDRow, error) {
	row := q.db.QueryRow(ctx, getPostScheduleByID, id)
	var i GetPostScheduleByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.ScheduledTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPostSchedulesByUserID = `-- name: ListPostSchedulesByUserID :many
SELECT id, user_id, post_id, scheduled_time, status, created_at, updated_at
FROM post_schedules
WHERE user_id = $1
ORDER BY scheduled_time DESC
LIMIT $2 OFFSET $3
`

type ListPostSchedulesByUserIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListPostSchedulesByUserIDRow struct {
	ID            pgtype.UUID      `json:"id"`
	UserID        pgtype.UUID      `json:"user_id"`
	PostID        pgtype.UUID      `json:"post_id"`
	ScheduledTime pgtype.Timestamp `json:"scheduled_time"`
	Status        string           `json:"status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListPostSchedulesByUserID(ctx context.Context, arg ListPostSchedulesByUserIDParams) ([]ListPostSchedulesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listPostSchedulesByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostSchedulesByUserIDRow
	for rows.Next() {
		var i ListPostSchedulesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PostID,
			&i.ScheduledTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const schedulePost = `-- name: SchedulePost :one
INSERT INTO post_schedules (
  user_id, post_id, social_account_id, scheduled_time, status
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, user_id, post_id, social_account_id, scheduled_time, executed_time, status, created_at, updated_at
`

type SchedulePostParams struct {
	UserID          pgtype.UUID      `json:"user_id"`
	PostID          pgtype.UUID      `json:"post_id"`
	SocialAccountID pgtype.UUID      `json:"social_account_id"`
	ScheduledTime   pgtype.Timestamp `json:"scheduled_time"`
	Status          string           `json:"status"`
}

func (q *Queries) SchedulePost(ctx context.Context, arg SchedulePostParams) (PostSchedule, error) {
	row := q.db.QueryRow(ctx, schedulePost,
		arg.UserID,
		arg.PostID,
		arg.SocialAccountID,
		arg.ScheduledTime,
		arg.Status,
	)
	var i PostSchedule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.SocialAccountID,
		&i.ScheduledTime,
		&i.ExecutedTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePostSchedule = `-- name: UpdatePostSchedule :one
UPDATE post_schedules
SET scheduled_time = $2,
    status = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, post_id, social_account_id, scheduled_time, executed_time, status, created_at, updated_at
`

type UpdatePostScheduleParams struct {
	ID            pgtype.UUID      `json:"id"`
	ScheduledTime pgtype.Timestamp `json:"scheduled_time"`
	Status        string           `json:"status"`
}

func (q *Queries) UpdatePostSchedule(ctx context.Context, arg UpdatePostScheduleParams) (PostSchedule, error) {
	row := q.db.QueryRow(ctx, updatePostSchedule, arg.ID, arg.ScheduledTime, arg.Status)
	var i PostSchedule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.SocialAccountID,
		&i.ScheduledTime,
		&i.ExecutedTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
