// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BulkCreatePostSuggestions(ctx context.Context, arg BulkCreatePostSuggestionsParams) ([]BulkCreatePostSuggestionsRow, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreatePostSchedule(ctx context.Context, arg CreatePostScheduleParams) (Postschedule, error)
	CreatePostSuggestion(ctx context.Context, arg CreatePostSuggestionParams) (Postsuggestion, error)
	CreatePrompt(ctx context.Context, arg CreatePromptParams) (Prompt, error)
	CreateSocialAccount(ctx context.Context, arg CreateSocialAccountParams) (Socialaccount, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (Verifyemail, error)
	DeletePost(ctx context.Context, id pgtype.UUID) (Post, error)
	DeletePostSchedule(ctx context.Context, id pgtype.UUID) (Postschedule, error)
	DeletePostSuggestion(ctx context.Context, id pgtype.UUID) (Postsuggestion, error)
	DeletePrompt(ctx context.Context, id pgtype.UUID) (Prompt, error)
	DeleteSocialAccount(ctx context.Context, id pgtype.UUID) (Socialaccount, error)
	GetPostByID(ctx context.Context, id pgtype.UUID) (GetPostByIDRow, error)
	GetPostScheduleByID(ctx context.Context, id pgtype.UUID) (GetPostScheduleByIDRow, error)
	GetPostSuggestionByID(ctx context.Context, id pgtype.UUID) (Postsuggestion, error)
	GetPromptByID(ctx context.Context, id pgtype.UUID) (Prompt, error)
	GetPromptByUserIDAndText(ctx context.Context, arg GetPromptByUserIDAndTextParams) (Prompt, error)
	GetSocialAccountByID(ctx context.Context, id pgtype.UUID) (GetSocialAccountByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	ListPostSchedulesByUserID(ctx context.Context, arg ListPostSchedulesByUserIDParams) ([]ListPostSchedulesByUserIDRow, error)
	ListPostSuggestionsByPromptID(ctx context.Context, arg ListPostSuggestionsByPromptIDParams) ([]Postsuggestion, error)
	ListPostsByUserID(ctx context.Context, arg ListPostsByUserIDParams) ([]ListPostsByUserIDRow, error)
	ListPromptsByUserID(ctx context.Context, arg ListPromptsByUserIDParams) ([]Prompt, error)
	ListSocialAccountsByUserID(ctx context.Context, arg ListSocialAccountsByUserIDParams) ([]ListSocialAccountsByUserIDRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdatePostSchedule(ctx context.Context, arg UpdatePostScheduleParams) (Postschedule, error)
	UpdatePostSuggestion(ctx context.Context, arg UpdatePostSuggestionParams) (Postsuggestion, error)
	UpdatePrompt(ctx context.Context, arg UpdatePromptParams) (Prompt, error)
	UpdateSocialAccount(ctx context.Context, arg UpdateSocialAccountParams) (Socialaccount, error)
	UpdateSocialAccountToken(ctx context.Context, arg UpdateSocialAccountTokenParams) (Socialaccount, error)
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (Verifyemail, error)
}

var _ Querier = (*Queries)(nil)
