// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BulkCreatePostSuggestions(ctx context.Context, arg BulkCreatePostSuggestionsParams) ([]BulkCreatePostSuggestionsRow, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreatePostSuggestion(ctx context.Context, arg CreatePostSuggestionParams) (PostSuggestion, error)
	CreatePrompt(ctx context.Context, arg CreatePromptParams) (Prompt, error)
	CreateSocialAccount(ctx context.Context, arg CreateSocialAccountParams) (SocialAccount, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	DeletePost(ctx context.Context, id pgtype.UUID) (Post, error)
	DeletePostSuggestion(ctx context.Context, id pgtype.UUID) (PostSuggestion, error)
	DeletePrompt(ctx context.Context, id pgtype.UUID) (Prompt, error)
	DeleteSchedule(ctx context.Context, id pgtype.UUID) (PostSchedule, error)
	DeleteSocialAccount(ctx context.Context, id pgtype.UUID) (SocialAccount, error)
	GetPostByID(ctx context.Context, id pgtype.UUID) (Post, error)
	GetPostScheduleByID(ctx context.Context, id pgtype.UUID) (GetPostScheduleByIDRow, error)
	GetPostSuggestionByID(ctx context.Context, id pgtype.UUID) (GetPostSuggestionByIDRow, error)
	GetPromptByID(ctx context.Context, id pgtype.UUID) (Prompt, error)
	GetPromptByUserIDAndText(ctx context.Context, arg GetPromptByUserIDAndTextParams) (Prompt, error)
	GetScheduledPostsWithinTimeframe(ctx context.Context, arg GetScheduledPostsWithinTimeframeParams) ([]GetScheduledPostsWithinTimeframeRow, error)
	GetSocialAccountByID(ctx context.Context, id pgtype.UUID) (GetSocialAccountByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	ListPostSchedulesByUserID(ctx context.Context, arg ListPostSchedulesByUserIDParams) ([]ListPostSchedulesByUserIDRow, error)
	ListPostSuggestionsByPromptID(ctx context.Context, arg ListPostSuggestionsByPromptIDParams) ([]ListPostSuggestionsByPromptIDRow, error)
	ListPostsByUserID(ctx context.Context, arg ListPostsByUserIDParams) ([]ListPostsByUserIDRow, error)
	ListPromptsByUserID(ctx context.Context, arg ListPromptsByUserIDParams) ([]Prompt, error)
	ListSocialAccountsByUserID(ctx context.Context, arg ListSocialAccountsByUserIDParams) ([]ListSocialAccountsByUserIDRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	SchedulePost(ctx context.Context, arg SchedulePostParams) (PostSchedule, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdatePostSchedule(ctx context.Context, arg UpdatePostScheduleParams) (PostSchedule, error)
	UpdatePostScheduleExectued(ctx context.Context, id pgtype.UUID) (PostSchedule, error)
	UpdatePostStatus(ctx context.Context, arg UpdatePostStatusParams) (Post, error)
	UpdatePostSuggestionStatus(ctx context.Context, arg UpdatePostSuggestionStatusParams) (PostSuggestion, error)
	UpdatePrompt(ctx context.Context, arg UpdatePromptParams) (Prompt, error)
	UpdateSocialAccount(ctx context.Context, arg UpdateSocialAccountParams) (SocialAccount, error)
	UpdateSocialAccountToken(ctx context.Context, arg UpdateSocialAccountTokenParams) (SocialAccount, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error)
}

var _ Querier = (*Queries)(nil)
