apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::050752639725:user/ci-user
      username: ci-user
      groups:
        - system:masters